// Mock state for the AeroSpork Settings recreation. Values match the shipped default config.
window.AS_DATA = {
  monitors: [
    { id: 'm1', name: 'Built-in Retina Display', resolution: '1728 × 1117 pt', uuid: 'BBBBBBBB-0000-4000-8000-000000000002' },
    { id: 'm2', name: 'DELL U2720Q', resolution: '2560 × 1440 pt', uuid: 'AAAAAAAA-0000-4000-8000-000000000001' },
    { id: 'm3', name: 'DisplayLink Monitor', resolution: '1920 × 1080 pt', uuid: 'CCCCCCCC-0000-4000-8000-000000000003' },
  ],
  assignments: [
    { id: 'a1', workspace: '1', monitor: 'main' },
    { id: 'a2', workspace: 'web', monitor: 'AAAAAAAA-0000-4000-8000-000000000001' },
  ],
  bindings: {
    main: [
      { id: 'g1', key: 'alt-h', command: 'focus left', origin: 'generated' },
      { id: 'g2', key: 'alt-j', command: 'focus down', origin: 'generated' },
      { id: 'g3', key: 'alt-k', command: 'focus up', origin: 'generated' },
      { id: 'g4', key: 'alt-l', command: 'focus right', origin: 'generated' },
      { id: 'g5', key: 'alt-shift-h', command: 'move left', origin: 'generated' },
      { id: 'g6', key: 'alt-minus', command: 'resize smart -50', origin: 'generated' },
      { id: 'g7', key: 'alt-slash', command: 'layout tiles horizontal vertical', origin: 'generated' },
      { id: 'g8', key: 'alt-tab', command: 'workspace-back-and-forth', origin: 'generated' },
      { id: 'e1', key: 'alt-shift-semicolon', command: 'mode service', origin: 'explicit' },
      { id: 'e2', key: 'alt-enter', command: 'exec-and-forget open -na Ghostty', origin: 'explicit' },
    ],
    service: [
      { id: 's1', key: 'esc', command: 'reload-config ; mode main', origin: 'explicit' },
      { id: 's2', key: 'r', command: 'flatten-workspace-tree ; mode main', origin: 'explicit' },
      { id: 's3', key: 'f', command: 'layout floating tiling ; mode main', origin: 'explicit' },
      { id: 's4', key: 'backspace', command: 'close-all-windows-but-current ; mode main', origin: 'explicit' },
    ],
  },
  rules: [
    { id: 'r1', appId: 'com.apple.mail', appNameRegex: '', windowTitleRegex: '', workspace: '', run: 'move-node-to-workspace 3', checkFurther: false, duringStartup: false },
    { id: 'r2', appId: 'com.apple.systempreferences', appNameRegex: '', windowTitleRegex: '', workspace: '', run: 'layout floating', checkFurther: false, duringStartup: false },
    { id: 'r3', appId: 'com.spotify.client', appNameRegex: '', windowTitleRegex: '', workspace: '', run: 'move-node-to-workspace media', checkFurther: false, duringStartup: true },
  ],
  events: {
    afterStartup: ['exec-and-forget sketchybar --reload'],
    workspaceChanged: ['move-mouse window-lazy-center'],
    monitorChanged: [],
    focusChanged: [],
  },
  env: [{ id: 'v1', name: 'PATH', value: '/opt/homebrew/bin:/usr/bin:/bin' }],
  toml: [
    '# AeroSpork — tiling window manager for macOS',
    '',
    'mod = "alt"',
    'workspaces = "1-9"',
    '',
    '[gaps]',
    'inner = 8',
    'outer = { top = 32, bottom = 8, left = 8, right = 8 }',
    '',
    '[keys]',
    'alt-shift-semicolon = "mode service"',
    'alt-enter = "exec-and-forget open -na Ghostty"',
    '',
    '[keys.service]',
    'esc = ["reload-config", "mode main"]',
    'r = ["flatten-workspace-tree", "mode main"]',
    '',
    '[monitors]',
    '1 = "main"',
    'web = { uuid = "AAAAAAAA-0000-4000-8000-000000000001" }',
    '',
    '[on-window]',
    '"com.apple.mail" = "move-node-to-workspace 3"',
  ].join('\n'),
};
