#!/bin/bash
cd "$(dirname "$0")/.."
source ./script/setup.sh

zip_uri='' # mandatory
cask_name='' # mandatory
build_version="0.0.0-SNAPSHOT"
# Must match what build-release.sh actually packs. publish-release.sh calls this script without
# --app-bundle-dir-name, and the old default ('AeroSpork.app') produced a cask that pointed at a
# path the zip does not contain -- invisible on case-insensitive APFS, a 404 everywhere else.
app_bundle_dir_name='AeroSpork.app'
while test $# -gt 0; do
    case $1 in
        --build-version) build_version="$2"; shift 2;;
        --zip-uri) zip_uri="$2"; shift 2;;
        --app-bundle-dir-name) app_bundle_dir_name="$2"; shift 2;;
        --cask-name) cask_name="$2"; shift 2;;
        *) echo "Unknown arg $1"; exit 1;;
    esac
done

if test -z "$zip_uri"; then echo "--zip-uri is mandatory" > /dev/stderr; exit 1; fi
if test -z "$cask_name"; then echo "--cask-name is mandatory" > /dev/stderr; exit 1; fi

case "$cask_name" in
    # No `conflicts_with` on the published cask. A cask submitted to Homebrew/homebrew-cask must not
    # name a token that does not exist in that tap, and `aerospork-dev` never will. Nothing is lost:
    # install-from-sources.sh uninstalls both casks unconditionally before installing the dev one.
    aerospork) conflicts_with_casks="";;
    aerospork-dev) conflicts_with_casks="  conflicts_with cask: \"aerospork\"";;
    *) echo "Unknown cask name: $cask_name. Allowed cask names: aerospork, aerospork-dev" > /dev/stderr; exit 1;;
esac

zip_file=''
if test -f "$zip_uri"; then
    zip_file=$zip_uri
    zip_uri="file://$(realpath "$zip_file")"
elif grep -q '^http' <<< "$zip_uri"; then
    zip_file=/tmp/AeroSpork-tmp.zip
    rm -rf $zip_file
    curl -L "$zip_uri" -o $zip_file
else
    echo "$zip_uri doesn't exist" > /dev/stderr; exit 1
fi
sha=$(shasum -a 256 "$zip_file" | awk '{print $1}')

cask_version=':latest' # Prevent 'Not upgrading aerospork, the latest version is already installed'
zip_root_dir="aerospork-v$build_version"
# Both are illegal next to `version :latest` -- `brew audit` rejects a livecheck beside it
# (audit_latest_with_livecheck) and `auto_updates` beside it (audit_latest_with_auto_updates), so a
# SNAPSHOT build gets neither.
livecheck_stanza=""
auto_updates_stanza=""
if ! grep -q SNAPSHOT <<< "$build_version"; then
    # Double quotes, not single: `brew style` (RuboCop Style/StringLiterals) rejects single-quoted
    # strings in casks, and a tap that does not pass `brew style` is one Homebrew will not take.
    cask_version="\"$build_version\""
    zip_root_dir=$(sed "s/$build_version/#{version}/g" <<< "$zip_root_dir")
    zip_uri=$(sed "s/$build_version/#{version}/g" <<< "$zip_uri")
    # The app updates itself through Sparkle. Without this stanza Homebrew believes it owns the
    # installed version and the two disagree after the first in-app update.
    auto_updates_stanza="  auto_updates true"
    # Only the published cask. The dev cask is installed from a local file:// zip built from
    # whatever is checked out, so the public appcast is the wrong answer about what is installed.
    #
    # The trailing blank line is deliberate: `livecheck` is its own stanza group, and
    # `brew style` (Cask/StanzaGrouping) wants it separated from what follows.
    if test "$cask_name" = aerospork; then
        livecheck_stanza="  livecheck do
    url \"https://aerospork.app/appcast.xml\"
    strategy :sparkle
  end
"
    fi
fi

# Joined here rather than given a template line each. An optional stanza that is skipped leaves its
# line behind as a blank, and a blank line *between* stanzas of one group is a `brew style`
# (Cask/StanzaGrouping) failure that no amount of squeezing afterwards can fix.
group_stanzas=$(printf '%s\n' "$auto_updates_stanza" "$conflicts_with_casks" | grep -v '^$' || true)

manpages=$(unzip -l "$zip_file" | \
    grep --only-matching 'manpage/aerospork.*' | \
    while read -r it; do echo "  manpage \"$zip_root_dir/$it\""; done | \
    sort)

rm -f ".release/$cask_name.rb" || true
mkdir -p .release
# Piped through `cat -s` because which stanzas appear depends on the cask and the version, and a
# skipped one leaves its template line behind as a blank. Squeezing runs of blank lines to one is
# exactly what is wanted here: every optional stanza sits at a group boundary, where one blank line
# is correct and two are a `brew style` (Layout/EmptyLines) failure.
cat <<EOF | cat -s > ".release/$cask_name.rb"
cask "$cask_name" do # THE FILE IS GENERATED BY build-brew-cask.sh
  version $cask_version
  sha256 "$sha"

  url "$zip_uri"
  name "AeroSpork"
  # \`brew style\` (Cask/Desc) rejects a desc that opens with the cask name, opens with an article,
  # or names the platform -- so not "AeroSpork is an i3-like tiling window manager for macOS",
  # which is how the prose reads everywhere else. Homebrew already shows the name and the platform.
  desc "Tiling window manager with i3-like tree layout"
  homepage "https://github.com/wbsmolen/aerospork"

$livecheck_stanza
$group_stanzas
  # \`macos: :ventura\` is the MINIMUM, not an exact match -- Homebrew's OSDependsOn cop rewrites
  # ">= :ventura" to exactly this, so the two are the same requirement.
  depends_on macos: :ventura # macOS 13

  # No quarantine-stripping postflight. It used to run
  #   xattr -d com.apple.quarantine ...
  # which Homebrew rejects in submitted casks, and which did nothing for anyone downloading the
  # zip directly — it only worked because brew happened to run it locally. The real fix is
  # notarization (see build-release.sh), which makes Gatekeeper accept the app on any Mac.

  app "$zip_root_dir/$app_bundle_dir_name"
  # The CLI is shipped INSIDE the app bundle, and this points at the installed copy rather than at
  # the zip's bin/ (which is only a symlink into the same place). A standalone copy on disk would be
  # a bare Mach-O, and a notarization ticket cannot be stapled to one of those -- Apple's own
  # \`syspolicy_check distribution\` calls that "Notary Ticket Missing ... Severity: Fatal". Inside
  # the bundle it is covered by the app's stapled ticket and works with no network.
  binary "#{appdir}/$app_bundle_dir_name/Contents/MacOS/aerospork-cli", target: "aerospork"
  # \`target:\` lines align under the first argument (Layout/ArgumentAlignment), not at a fixed
  # indent.
  binary "$zip_root_dir/shell-completion/zsh/_aerospork",
         target: "#{HOMEBREW_PREFIX}/share/zsh/site-functions/_aerospork"
  binary "$zip_root_dir/shell-completion/bash/aerospork",
         target: "#{HOMEBREW_PREFIX}/etc/bash_completion.d/aerospork"
  binary "$zip_root_dir/shell-completion/fish/aerospork.fish",
         target: "#{HOMEBREW_PREFIX}/share/fish/vendor_completions.d/aerospork.fish"
$manpages

  # Everything the app writes outside its own bundle. Both casks install the same release
  # \`AeroSpork.app\`, so both carry bundle id com.wbs.aerospork and these paths are correct for
  # either. Not listed: the CLI socket in /tmp, which is recreated every launch, and the
  # SMAppService login item, which macOS drops with the app.
  #
  # \`~/.config/aerospork\` is the XDG config location with XDG_CONFIG_HOME unset. A user who has
  # set that variable elsewhere keeps their config -- brew cannot see the environment the app ran in.
  zap trash: [
    "~/.aerospork.toml",
    "~/.config/aerospork",
    "~/Library/Caches/com.wbs.aerospork",
    "~/Library/HTTPStorages/com.wbs.aerospork",
    "~/Library/Preferences/com.wbs.aerospork.plist",
    "~/Library/Saved Application State/com.wbs.aerospork.savedState",
  ]
end
EOF
