= aerospork-move-node-to-monitor(1)
include::util/man-attributes.adoc[]
:manname: aerospork-move-node-to-monitor
// tag::purpose[]
:manpurpose: Move window to monitor targeted by relative direction, by order, or by pattern
// end::purpose[]

// =========================================================== Synopsis
== Synopsis
[verse]
// tag::synopsis[]
aerospork move-node-to-monitor [-h|--help] [--window-id <window-id>] [--focus-follows-window]
                               [--wrap-around] (left|down|up|right|next|prev)
aerospork move-node-to-monitor [-h|--help] [--window-id <window-id>] [--focus-follows-window]
                               [--fail-if-noop] <monitor-pattern>...

// end::synopsis[]

// =========================================================== Description
== Description

// tag::body[]
{manpurpose}

// =========================================================== Options
include::util/conditional-options-header.adoc[]

-h, --help:: Print help
--wrap-around:: Make it possible to wrap around the movement

--focus-follows-window::
Make sure that the window in question receives focus after moving.
This flag is a shortcut for manually running `aerospork-workspace`/`aerospork-focus` after `move-node-to-monitor` successful execution.

--fail-if-noop::
Exit with a non-zero exit code if the window already belongs to the target monitor

--window-id <window-id>::
include::util/window-id-flag-desc.adoc[]

// =========================================================== Arguments
include::util/conditional-arguments-header.adoc[]

(left|down|up|right)::
Move window to monitor in direction relative to the focused monitor

(next|prev)::
Move window to next|prev monitor in the order they appear in the menu bar icon

<monitor-pattern>...::
Find the first matching monitor and move the window there.
Multiple monitor patterns are useful for covering different monitor configurations.
Monitor patterns follow the same format as in `workspace-to-monitor-force-assignment` config option

// end::body[]

// =========================================================== Footer
include::util/man-footer.adoc[]
