= aerospork-layout(1)
include::util/man-attributes.adoc[]
:manname: aerospork-layout
// tag::purpose[]
:manpurpose: Change layout of the focused window to the given layout
// end::purpose[]

// =========================================================== Synopsis
== Synopsis
[verse]
// tag::synopsis[]
aerospork layout [-h|--help] [--window-id <window-id>]
                 (h_tiles|v_tiles|h_accordion|v_accordion|tiles|accordion|horizontal|vertical|tiling|floating)...

// end::synopsis[]

// =========================================================== Description
== Description

// tag::body[]
{manpurpose}

If several arguments are supplied then finds the first argument that doesn't describe the currently active layout, and applies the layout.

* Change both tiling layout and orientation in one go: `h_tiles|v_tiles|h_accordion|v_accordion`
* Change tiling layout but preserve orientation: `tiles|accordion`
* Change orientation but preserve layout: `horizontal|vertical`
* Toggle floating/tiling mode: `tiling|floating`

Deprecated (but still supported) layout names: `list`, `h_list`, `v_list` for `tiles`, `h_tiles`, `v_tiles`

// =========================================================== Options
include::util/conditional-options-header.adoc[]

-h, --help:: Print help

--window-id <window-id>::
include::util/window-id-flag-desc.adoc[]

// =========================================================== Examples
include::util/conditional-examples-header.adoc[]

* Toggle between `floating` and `tiling` layouts (order of args doesn't matter): +
`aerospork layout floating tiling`

* Toggle orientation (order of args doesn't matter): +
`aerospork layout horizontal vertical`

* Toggle between `tiles` and `accordion` layouts (order of args doesn't matter): +
`aerospork layout tiles accordion`

* Switch to `tiles` layout. Toggle the layout orientation if already in `tiles` layout: +
`aerospork layout tiles horizontal vertical`

// end::body[]

// =========================================================== Footer
include::util/man-footer.adoc[]
