= aerospork-focus-monitor(1)
include::util/man-attributes.adoc[]
:manname: aerospork-focus-monitor
// tag::purpose[]
:manpurpose: Focus monitor by relative direction, by order, or by pattern
// end::purpose[]

// =========================================================== Synopsis
== Synopsis
[verse]
// tag::synopsis[]
aerospork focus-monitor [-h|--help] [--wrap-around] (left|down|up|right)
aerospork focus-monitor [-h|--help] [--wrap-around] (next|prev)
aerospork focus-monitor [-h|--help] <monitor-pattern>...

// end::synopsis[]

// =========================================================== Description
== Description

// tag::body[]
{manpurpose}

// =========================================================== Options
include::util/conditional-options-header.adoc[]

-h, --help:: Print help
--wrap-around:: Make it possible to wrap around focus

// =========================================================== Arguments
include::util/conditional-arguments-header.adoc[]

(left|down|up|right)::
Focus monitor in direction relative to the focused monitor

(next|prev)::
Focus next|prev monitor in the order they appear in the menu bar icon

<monitor-pattern>...::
Find the first matching monitor and focus it.
Multiple monitor patterns are useful for covering different monitor configurations.
Monitor patterns follow the same format as in the `[monitors]` config section
(previously `workspace-to-monitor-force-assignment`, still accepted)

// end::body[]

// =========================================================== Footer
include::util/man-footer.adoc[]
